Repository brokenManager/gakkouike, pull requests merged in 2020-03, with the labels that each got.

#45 †追加† 週ごとの時間数を入力するだけで自動で計算できるようになった
  lib/custom_types/subject.dart
  lib/data_manager/subject_adder.dart
Labels: enhancement

#46 †追加† 初期設定UIにエモみを加えてバグを修正した
  lib/config/inital_config.dart
Labels: enhancement

#52 [enchant] Issue #50 を実装
  android/app/build.gradle
  lib/config/config.dart
Labels: enhancement

#64 †追加† ムキーッ！2時間も次回使っちまいましたわよ！
  lib/calendar/calendar.dart
Labels: Ganbare Tsuyotsuyo

#63 †追加† UFIに準拠したUIを追加した
  lib/main.dart
Labels: UFI violation
